#!/usr/bin/env bash

if xrandr | grep "HDMI-0 disconnected"; then
    if xrandr | grep "DP-1 disconnected"; then
        xrandr --output LVDS-0 --primary --auto
        xrandr --dpi 86
    else
        xrandr --output LVDS-0 --primary --auto
        xrandr --output DP-1 --auto
        xrandr --output LVDS-0 --right-of DP-1 --auto
        xrandr --dpi 86
    fi
else
    xrandr --output LVDS-0 --off
    xrandr --output HDMI-0 --primary --auto
    xrandr --output DP-1 --auto
    xrandr --output HDMI-0 --auto --right-of DP-1 --auto
    xrandr --dpi 86
fi